package net.alphadev.icalendar.model

import net.alphadev.icalendar.model.dsl.vCalendar
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.time.Instant

class VFreeBusyDslTest {

    @Test
    fun freeBusyHasAutoGeneratedUidAndDtStamp() {
        val calendar = vCalendar {
            prodId("-//Test//EN")
            freeBusy { }
        }
        val fb = calendar.components.first() as VFreeBusy
        assertNotNull(fb.uid)
        assertNotNull(fb.dtStamp)
    }

    @Test
    fun createFreeBusyWithTimeRange() {
        val calendar = vCalendar {
            prodId("-//Test//EN")
            freeBusy {
                uid("fb-001")
                dtStart(Instant.parse("2024-06-15T10:00:00Z"))
                dtEnd(Instant.parse("2024-06-15T11:00:00Z"))
            }
        }

        val fb = calendar.components.first() as VFreeBusy
        assertEquals("fb-001", fb.uid)
        assertEquals(Instant.parse("2024-06-15T10:00:00Z"), fb.dtStart)
        assertEquals(Instant.parse("2024-06-15T11:00:00Z"), fb.dtEnd)
    }

    @Test
    fun createFreeBusyWithOrganizerAndAttendee() {
        val calendar = vCalendar {
            prodId("-//Test//EN")
            freeBusy {
                uid("fb-002")
                organizer("alice@example.com", "Alice")
                attendee("bob@example.com", "Bob")
            }
        }

        val fb = calendar.components.first() as VFreeBusy
        assertEquals("mailto:alice@example.com", fb.organizer)
        assertEquals(listOf("mailto:bob@example.com"), fb.attendees)
    }

    @Test
    fun createFreeBusyWithBusyPeriod() {
        val calendar = vCalendar {
            prodId("-//Test//EN")
            freeBusy {
                uid("fb-003")
                freeBusy("20240615T100000Z/20240615T110000Z")
            }
        }

        val fb = calendar.components.first() as VFreeBusy
        assertEquals(listOf("20240615T100000Z/20240615T110000Z"), fb.freeBusyPeriods)
    }

    @Test
    fun createFreeBusyWithMultiplePeriods() {
        val calendar = vCalendar {
            prodId("-//Test//EN")
            freeBusy {
                uid("fb-004")
                freeBusy("20240615T100000Z/20240615T110000Z")
                freeBusy("20240615T140000Z/20240615T150000Z")
            }
        }

        val fb = calendar.components.first() as VFreeBusy
        assertEquals(2, fb.freeBusyPeriods.size)
    }

    @Test
    fun createFreeBusyWithExplicitFbType() {
        val calendar = vCalendar {
            prodId("-//Test//EN")
            freeBusy {
                uid("fb-005")
                freeBusy("20240615T100000Z/20240615T110000Z", "BUSY_TENTATIVE")
            }
        }

        val fb = calendar.components.first() as VFreeBusy
        val fbProp = fb.properties.first { it.name == "FREEBUSY" }
        assertEquals(listOf("BUSY_TENTATIVE"), fbProp.parameters["FBTYPE"])
    }

    @Test
    fun vCalendarContainsFreeBusyComponent() {
        val calendar = vCalendar {
            prodId("-//Test//EN")
            freeBusy { uid("fb-006") }
        }

        assertEquals(1, calendar.components.filterIsInstance<VFreeBusy>().size)
    }
}
